export const AUTH_ERROR_CODES = {
  // QBO Errors
  QBO_REAUTH_REQUIRED: 'QBO_REAUTH_REQUIRED',
  QBO_TOKEN_EXPIRED: 'QBO_TOKEN_EXPIRED',
  QBO_REFRESH_FAILED: 'QBO_REFRESH_FAILED',
  QBO_INVALID_TOKEN: 'QBO_INVALID_TOKEN',
  QBO_CONNECTION_FAILED: 'QBO_CONNECTION_FAILED',
  
  // Xero Errors
  XERO_REAUTH_REQUIRED: 'XERO_REAUTH_REQUIRED',
  XERO_TOKEN_EXPIRED: 'XERO_TOKEN_EXPIRED',
  XERO_REFRESH_FAILED: 'XERO_REFRESH_FAILED',
  XERO_INVALID_TOKEN: 'XERO_INVALID_TOKEN',
  XERO_CONNECTION_FAILED: 'XERO_CONNECTION_FAILED',
  
  // General Errors
  INVALID_CONNECTION_TYPE: 'INVALID_CONNECTION_TYPE',
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  TOKEN_STORAGE_FAILED: 'TOKEN_STORAGE_FAILED',
  TOKEN_RETRIEVAL_FAILED: 'TOKEN_RETRIEVAL_FAILED',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',
  
  // Audit Errors
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
  AUDIT_UPDATE_FAILED: 'AUDIT_UPDATE_FAILED',
} as const;

export type AuthErrorCode = typeof AUTH_ERROR_CODES[keyof typeof AUTH_ERROR_CODES];
